name: water2
channels:
  - defaults
dependencies:
  - keras-applications=1.0.8=py_0
  - keras-preprocessing=1.1.0=py_1
  - pip=19.1.1=py36_0
  - python=3.6.9=5
  - scipy=1.3.1=py36ha68da19_2
  - tensorboard=1.15.0=pyhb230dea_0
  - tensorflow=1.15.2=py36_0
  - tensorflow-base=1.15.2=0
  - tensorflow-estimator=1.15.1=pyh2649769_0
  - pip:
    - keras==2.2.5


